"""add_campaign_point_referral_tables

Revision ID: c4dd004ede4f
Revises: add_pet_recommendation
Create Date: 2026-02-10 16:47:53.286368

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'c4dd004ede4f'
down_revision = 'add_pet_recommendation'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('key', sa.Text(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('placement', sa.String(length=30), nullable=False),
    sa.Column('template', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.Integer(), server_default='100', nullable=False),
    sa.Column('is_enabled', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('content', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('idx_campaigns_active', 'campaigns', ['is_enabled', 'start_at', 'end_at', 'priority'], unique=False)
    op.create_table('campaign_actions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('trigger', sa.String(length=50), nullable=False),
    sa.Column('action_type', sa.String(length=30), nullable=False),
    sa.Column('action', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_actions_campaign', 'campaign_actions', ['campaign_id'], unique=False)
    op.create_index('idx_campaign_actions_trigger', 'campaign_actions', ['trigger'], unique=False)
    op.create_table('campaign_rules',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('rule', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_campaign_rules_campaign', 'campaign_rules', ['campaign_id'], unique=False)
    op.create_index('idx_campaign_rules_gin', 'campaign_rules', ['rule'], unique=False, postgresql_using='gin')
    op.create_table('point_ledger',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('delta', sa.Integer(), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('ref_type', sa.String(length=50), nullable=True),
    sa.Column('ref_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_point_ledger_user', 'point_ledger', ['user_id'], unique=False)
    op.create_table('point_wallets',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('balance', sa.Integer(), server_default='0', nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('referral_codes',
    sa.Column('inviter_user_id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['inviter_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('inviter_user_id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('user_campaign_impressions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('seen_count', sa.Integer(), server_default='1', nullable=False),
    sa.Column('suppress_until', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'campaign_id', name='uq_user_campaign_impression')
    )
    op.create_index('idx_user_campaign_impressions_user', 'user_campaign_impressions', ['user_id'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('invitee_user_id', sa.UUID(), nullable=True),
    sa.Column('invitee_device_id', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('confirmed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['code'], ['referral_codes.code'], ),
    sa.ForeignKeyConstraint(['invitee_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('invitee_user_id', name='uq_referral_invitee_user')
    )
    op.create_index('idx_referrals_code', 'referrals', ['code'], unique=False)
    op.create_index('idx_referrals_status', 'referrals', ['status'], unique=False)
    op.create_table('user_campaign_rewards',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('campaign_id', sa.UUID(), nullable=False),
    sa.Column('action_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('idempotency_key', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['action_id'], ['campaign_actions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'campaign_id', 'action_id', name='uq_user_campaign_reward')
    )
    op.create_index('idx_user_campaign_rewards_user', 'user_campaign_rewards', ['user_id'], unique=False)
    op.drop_index('idx_admin_import_log_rows_log', table_name='admin_import_log_rows')
    op.drop_table('admin_import_log_rows')
    op.drop_index('idx_pet_avoid_allergens_code', table_name='pet_avoid_allergens')
    op.drop_index('idx_pet_avoid_allergens_pet', table_name='pet_avoid_allergens')
    op.drop_table('pet_avoid_allergens')
    op.drop_index('idx_pet_health_conditions_condition', table_name='pet_health_conditions')
    op.drop_index('idx_pet_health_conditions_pet', table_name='pet_health_conditions')
    op.drop_table('pet_health_conditions')
    op.drop_index('idx_pet_product_preferences_pet', table_name='pet_product_preferences')
    op.drop_index('idx_pet_product_preferences_product', table_name='pet_product_preferences')
    op.drop_table('pet_product_preferences')
    op.drop_index('idx_admin_audit_created', table_name='admin_audit_logs')
    op.drop_index('idx_admin_audit_table_record', table_name='admin_audit_logs')
    op.drop_table('admin_audit_logs')
    op.drop_index('idx_admin_import_logs_started', table_name='admin_import_logs')
    op.drop_index('idx_admin_import_logs_status', table_name='admin_import_logs')
    op.drop_table('admin_import_logs')
    op.drop_index('idx_alert_events_alert_time', table_name='alert_events')
    op.create_index('idx_alert_events_alert_time', 'alert_events', ['alert_id', 'sent_at'], unique=False, postgresql_ops={'sent_at': 'DESC'})
    op.drop_index('idx_clicks_product_time', table_name='outbound_clicks')
    op.create_index('idx_clicks_product_time', 'outbound_clicks', ['product_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.drop_index('idx_clicks_user_time', table_name='outbound_clicks')
    op.create_index('idx_clicks_user_time', 'outbound_clicks', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.alter_column('pets', 'is_neutered',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_pets_current_product_id', table_name='pets')
    op.drop_index('idx_pets_species_age_stage', table_name='pets')
    op.drop_constraint('fk_pets_current_product', 'pets', type_='foreignkey')
    op.drop_column('pets', 'activity_level')
    op.drop_column('pets', 'current_product_id')
    op.drop_column('pets', 'note')
    op.drop_column('pets', 'current_food_started_at')
    op.drop_index('idx_price_snapshots_offer_time', table_name='price_snapshots')
    op.create_index('idx_price_snapshots_offer_time', 'price_snapshots', ['offer_id', 'captured_at'], unique=False, postgresql_ops={'captured_at': 'DESC'})
    op.drop_column('product_allergens', 'admin_note')
    op.drop_column('product_claims', 'admin_note')
    op.drop_constraint('fk_ingredient_profiles_last_updated_by', 'product_ingredient_profiles', type_='foreignkey')
    op.drop_column('product_ingredient_profiles', 'last_updated_by')
    op.drop_column('product_ingredient_profiles', 'is_manual_input')
    op.drop_constraint('fk_nutrition_facts_last_updated_by', 'product_nutrition_facts', type_='foreignkey')
    op.drop_column('product_nutrition_facts', 'last_updated_by')
    op.drop_column('product_nutrition_facts', 'is_manual_input')
    op.drop_index('idx_product_offers_current_price', table_name='product_offers')
    op.drop_index('idx_product_offers_last_fetch', table_name='product_offers')
    op.drop_index('idx_product_offers_product_priority', table_name='product_offers')
    op.drop_column('product_offers', 'last_seen_price')
    op.drop_column('product_offers', 'last_fetch_status')
    op.drop_column('product_offers', 'platform_image_url')
    op.drop_column('product_offers', 'last_fetch_error')
    op.drop_column('product_offers', 'display_priority')
    op.drop_column('product_offers', 'current_price')
    op.drop_column('product_offers', 'currency')
    op.drop_column('product_offers', 'last_fetched_at')
    op.drop_column('product_offers', 'admin_note')
    # Drop view first before dropping column
    op.execute("DROP VIEW IF EXISTS v_products_completion_flags CASCADE")
    
    op.drop_index('idx_products_active_updated', table_name='products')
    op.drop_index('idx_products_completion_status', table_name='products')
    op.drop_constraint('fk_products_last_admin_user', 'products', type_='foreignkey')
    op.drop_column('products', 'completion_status')
    op.drop_column('products', 'manufacturer_code')
    op.drop_column('products', 'thumbnail_url')
    op.drop_column('products', 'images')
    op.drop_column('products', 'archived_at')
    op.drop_column('products', 'official_url')
    op.drop_column('products', 'admin_memo')
    op.drop_column('products', 'last_admin_updated_at')
    op.drop_column('products', 'primary_image_url')
    op.drop_column('products', 'last_admin_user_id')
    op.drop_index('idx_rec_runs_pet_time', table_name='recommendation_runs')
    op.create_index('idx_rec_runs_pet_time', 'recommendation_runs', ['pet_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_rec_runs_pet_time', table_name='recommendation_runs', postgresql_ops={'created_at': 'DESC'})
    op.create_index('idx_rec_runs_pet_time', 'recommendation_runs', ['pet_id', sa.text('created_at DESC')], unique=False)
    op.add_column('products', sa.Column('last_admin_user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('primary_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('last_admin_updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('admin_memo', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('official_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('archived_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('images', postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'[]'::jsonb"), autoincrement=False, nullable=False))
    op.add_column('products', sa.Column('thumbnail_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('manufacturer_code', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.add_column('products', sa.Column('completion_status', postgresql.ENUM('COMPLETE', 'MISSING_INGREDIENTS', 'MISSING_NUTRITION', 'MISSING_OFFERS', 'MISSING_TAGS', 'NEEDS_REVIEW', name='product_completion_status'), server_default=sa.text("'MISSING_INGREDIENTS'::product_completion_status"), autoincrement=False, nullable=False))
    op.create_foreign_key('fk_products_last_admin_user', 'products', 'users', ['last_admin_user_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_products_completion_status', 'products', ['completion_status', sa.text('last_admin_updated_at DESC NULLS LAST')], unique=False)
    op.create_index('idx_products_active_updated', 'products', ['is_active', sa.text('last_admin_updated_at DESC NULLS LAST')], unique=False)
    op.add_column('product_offers', sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_offers', sa.Column('last_fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('product_offers', sa.Column('currency', sa.CHAR(length=3), server_default=sa.text("'KRW'::bpchar"), autoincrement=False, nullable=False))
    op.add_column('product_offers', sa.Column('current_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('product_offers', sa.Column('display_priority', sa.SMALLINT(), server_default=sa.text("'10'::smallint"), autoincrement=False, nullable=False))
    op.add_column('product_offers', sa.Column('last_fetch_error', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_offers', sa.Column('platform_image_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.add_column('product_offers', sa.Column('last_fetch_status', postgresql.ENUM('SUCCESS', 'FAILED', 'PENDING', 'NOT_FETCHED', name='offer_fetch_status'), server_default=sa.text("'NOT_FETCHED'::offer_fetch_status"), autoincrement=False, nullable=False))
    op.add_column('product_offers', sa.Column('last_seen_price', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_index('idx_product_offers_product_priority', 'product_offers', ['product_id', 'display_priority'], unique=False)
    op.create_index('idx_product_offers_last_fetch', 'product_offers', ['last_fetch_status', sa.text('last_fetched_at DESC')], unique=False)
    op.create_index('idx_product_offers_current_price', 'product_offers', ['product_id', 'current_price'], unique=False)
    op.add_column('product_nutrition_facts', sa.Column('is_manual_input', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('product_nutrition_facts', sa.Column('last_updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_nutrition_facts_last_updated_by', 'product_nutrition_facts', 'users', ['last_updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('product_ingredient_profiles', sa.Column('is_manual_input', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.add_column('product_ingredient_profiles', sa.Column('last_updated_by', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_ingredient_profiles_last_updated_by', 'product_ingredient_profiles', 'users', ['last_updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('product_claims', sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('product_allergens', sa.Column('admin_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_index('idx_price_snapshots_offer_time', table_name='price_snapshots', postgresql_ops={'captured_at': 'DESC'})
    op.create_index('idx_price_snapshots_offer_time', 'price_snapshots', ['offer_id', sa.text('captured_at DESC')], unique=False)
    op.add_column('pets', sa.Column('current_food_started_at', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('current_product_id', sa.UUID(), autoincrement=False, nullable=True))
    op.add_column('pets', sa.Column('activity_level', postgresql.ENUM('LOW', 'MEDIUM', 'HIGH', name='activitylevel'), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_pets_current_product', 'pets', 'products', ['current_product_id'], ['id'], ondelete='SET NULL')
    op.create_index('idx_pets_species_age_stage', 'pets', ['species', 'age_stage'], unique=False)
    op.create_index('idx_pets_current_product_id', 'pets', ['current_product_id'], unique=False)
    op.alter_column('pets', 'is_neutered',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index('idx_clicks_user_time', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_clicks_user_time', 'outbound_clicks', ['user_id', sa.text('clicked_at DESC')], unique=False)
    op.drop_index('idx_clicks_product_time', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_clicks_product_time', 'outbound_clicks', ['product_id', sa.text('clicked_at DESC')], unique=False)
    op.drop_index('idx_alert_events_alert_time', table_name='alert_events', postgresql_ops={'sent_at': 'DESC'})
    op.create_index('idx_alert_events_alert_time', 'alert_events', ['alert_id', sa.text('sent_at DESC')], unique=False)
    op.create_table('admin_import_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('import_type', postgresql.ENUM('PRODUCTS', 'OFFERS', 'INGREDIENTS', 'ALLERGENS', 'CLAIMS', 'BULK_UPDATE', name='admin_import_type'), autoincrement=False, nullable=False),
    sa.Column('filename', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('row_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('success_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('failed_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('error_summary', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('admin_user_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('started_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('finished_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('status', postgresql.ENUM('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED', name='admin_import_status'), server_default=sa.text("'PENDING'::admin_import_status"), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['admin_user_id'], ['users.id'], name='fk_admin_import_logs_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='admin_import_logs_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('idx_admin_import_logs_status', 'admin_import_logs', ['status', sa.text('started_at DESC')], unique=False)
    op.create_index('idx_admin_import_logs_started', 'admin_import_logs', [sa.text('started_at DESC')], unique=False)
    op.create_table('admin_audit_logs',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('table_name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('record_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('action', postgresql.ENUM('INSERT', 'UPDATE', 'DELETE', 'BULK_INSERT', 'BULK_UPDATE', 'IMPORT', name='admin_audit_action'), autoincrement=False, nullable=False),
    sa.Column('changed_by', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('memo', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('ip_address', sa.VARCHAR(length=45), autoincrement=False, nullable=True),
    sa.Column('user_agent', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['changed_by'], ['users.id'], name='fk_admin_audit_logs_user', ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id', name='admin_audit_logs_pkey')
    )
    op.create_index('idx_admin_audit_table_record', 'admin_audit_logs', ['table_name', 'record_id'], unique=False)
    op.create_index('idx_admin_audit_created', 'admin_audit_logs', [sa.text('created_at DESC')], unique=False)
    op.create_table('pet_product_preferences',
    sa.Column('pet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('product_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('preference', postgresql.ENUM('LIKE', 'DISLIKE', 'NEUTRAL', name='tastepreference'), server_default=sa.text("'NEUTRAL'::tastepreference"), autoincrement=False, nullable=False),
    sa.Column('reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='pet_product_preferences_pet_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name='fk_pet_product_preferences_product'),
    sa.PrimaryKeyConstraint('pet_id', 'product_id', name='pet_product_preferences_pkey')
    )
    op.create_index('idx_pet_product_preferences_product', 'pet_product_preferences', ['product_id'], unique=False)
    op.create_index('idx_pet_product_preferences_pet', 'pet_product_preferences', ['pet_id'], unique=False)
    op.create_table('pet_health_conditions',
    sa.Column('pet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('condition_code', postgresql.ENUM('SKIN', 'JOINT', 'GI', 'KIDNEY', 'URINARY', 'DENTAL', 'DIABETES', 'HEART', 'LIVER', 'OBESITY', 'UNDERWEIGHT', name='healthconditioncode'), autoincrement=False, nullable=False),
    sa.Column('severity', sa.SMALLINT(), server_default=sa.text("'50'::smallint"), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('OWNER', 'VET', 'TRIAL', 'LAB', 'UNKNOWN', name='infosource'), server_default=sa.text("'OWNER'::infosource"), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('severity >= 0 AND severity <= 100', name='pet_health_conditions_severity_check'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='pet_health_conditions_pet_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id', 'condition_code', name='pet_health_conditions_pkey')
    )
    op.create_index('idx_pet_health_conditions_pet', 'pet_health_conditions', ['pet_id'], unique=False)
    op.create_index('idx_pet_health_conditions_condition', 'pet_health_conditions', ['condition_code'], unique=False)
    op.create_table('pet_avoid_allergens',
    sa.Column('pet_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('allergen_code', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('level', postgresql.ENUM('CONFIRMED', 'SUSPECTED', 'PREFERENCE', name='avoidlevel'), server_default=sa.text("'SUSPECTED'::avoidlevel"), autoincrement=False, nullable=False),
    sa.Column('confidence', sa.SMALLINT(), server_default=sa.text("'80'::smallint"), autoincrement=False, nullable=False),
    sa.Column('source', postgresql.ENUM('OWNER', 'VET', 'TRIAL', 'LAB', 'UNKNOWN', name='infosource'), server_default=sa.text("'OWNER'::infosource"), autoincrement=False, nullable=False),
    sa.Column('note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 100', name='pet_avoid_allergens_confidence_check'),
    sa.ForeignKeyConstraint(['allergen_code'], ['allergen_codes.code'], name='fk_pet_avoid_allergens_code'),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], name='pet_avoid_allergens_pet_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id', 'allergen_code', name='pet_avoid_allergens_pkey')
    )
    op.create_index('idx_pet_avoid_allergens_pet', 'pet_avoid_allergens', ['pet_id'], unique=False)
    op.create_index('idx_pet_avoid_allergens_code', 'pet_avoid_allergens', ['allergen_code'], unique=False)
    op.create_table('admin_import_log_rows',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('import_log_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('row_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('raw_row', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['import_log_id'], ['admin_import_logs.id'], name='admin_import_log_rows_import_log_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='admin_import_log_rows_pkey')
    )
    op.create_index('idx_admin_import_log_rows_log', 'admin_import_log_rows', ['import_log_id', 'row_number'], unique=False)
    op.drop_index('idx_user_campaign_rewards_user', table_name='user_campaign_rewards')
    op.drop_table('user_campaign_rewards')
    op.drop_index('idx_referrals_status', table_name='referrals')
    op.drop_index('idx_referrals_code', table_name='referrals')
    op.drop_table('referrals')
    op.drop_index('idx_user_campaign_impressions_user', table_name='user_campaign_impressions')
    op.drop_table('user_campaign_impressions')
    op.drop_table('referral_codes')
    op.drop_table('point_wallets')
    op.drop_index('idx_point_ledger_user', table_name='point_ledger')
    op.drop_table('point_ledger')
    op.drop_index('idx_campaign_rules_gin', table_name='campaign_rules', postgresql_using='gin')
    op.drop_index('idx_campaign_rules_campaign', table_name='campaign_rules')
    op.drop_table('campaign_rules')
    op.drop_index('idx_campaign_actions_trigger', table_name='campaign_actions')
    op.drop_index('idx_campaign_actions_campaign', table_name='campaign_actions')
    op.drop_table('campaign_actions')
    op.drop_index('idx_campaigns_active', table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###

