"""add_nickname_to_users_and_update_schema

Revision ID: ea321c242d86
Revises: ec9dc2d37528
Create Date: 2026-02-03 03:25:59.148904

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ea321c242d86'
down_revision = 'ec9dc2d37528'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ENUM 타입 생성 (먼저 생성해야 함)
    op.execute("DO $$ BEGIN CREATE TYPE petspecies AS ENUM ('DOG', 'CAT'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE ageinputmode AS ENUM ('BIRTHDATE', 'APPROX'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE petsex AS ENUM ('MALE', 'FEMALE', 'UNKNOWN'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE agestage AS ENUM ('PUPPY', 'ADULT', 'SENIOR'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    op.execute("DO $$ BEGIN CREATE TYPE recstrategy AS ENUM ('RULE_V1', 'RULE_V2', 'ML_V1'); EXCEPTION WHEN duplicate_object THEN null; END $$")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('allergen_codes',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # Insert initial allergen codes data
    op.execute("""
        INSERT INTO allergen_codes (code, display_name) VALUES
        ('BEEF', '소고기'),
        ('CHICKEN', '닭고기'),
        ('PORK', '돼지고기'),
        ('DUCK', '오리고기'),
        ('LAMB', '양고기'),
        ('FISH', '생선'),
        ('EGG', '계란'),
        ('DAIRY', '유제품'),
        ('WHEAT', '밀/글루텐'),
        ('CORN', '옥수수'),
        ('SOY', '콩')
        ON CONFLICT (code) DO NOTHING
    """)
    op.create_table('claim_codes',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('health_concern_codes',
    sa.Column('code', sa.String(length=30), nullable=False),
    sa.Column('display_name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('code')
    )
    # Insert initial health concern codes data
    op.execute("""
        INSERT INTO health_concern_codes (code, display_name) VALUES
        ('ALLERGY', '알레르기'),
        ('DIGESTIVE', '장/소화'),
        ('DENTAL', '치아/구강'),
        ('OBESITY', '비만'),
        ('RESPIRATORY', '호흡기'),
        ('SKIN', '피부/털'),
        ('JOINT', '관절'),
        ('EYE', '눈/눈물'),
        ('KIDNEY', '신장/요로'),
        ('HEART', '심장'),
        ('SENIOR', '노령')
        ON CONFLICT (code) DO NOTHING
    """)
    op.create_table('product_allergens',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('allergen_code', sa.String(length=30), nullable=False),
    sa.Column('confidence', sa.SmallInteger(), server_default='80', nullable=False),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.CheckConstraint('confidence BETWEEN 0 AND 100', name='product_allergens_confidence_check'),
    sa.ForeignKeyConstraint(['allergen_code'], ['allergen_codes.code'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'allergen_code')
    )
    op.create_index('idx_product_allergens_allergen', 'product_allergens', ['allergen_code'], unique=False)
    op.create_table('product_claims',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('claim_code', sa.String(length=30), nullable=False),
    sa.Column('evidence_level', sa.SmallInteger(), server_default='50', nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.CheckConstraint('evidence_level BETWEEN 0 AND 100', name='product_claims_evidence_check'),
    sa.ForeignKeyConstraint(['claim_code'], ['claim_codes.code'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id', 'claim_code')
    )
    op.create_index('idx_product_claims_claim', 'product_claims', ['claim_code'], unique=False)
    op.create_table('product_ingredient_profiles',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('ingredients_text', sa.Text(), nullable=True),
    sa.Column('additives_text', sa.Text(), nullable=True),
    sa.Column('parsed', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('source', sa.String(length=200), nullable=True),
    sa.Column('updated_at', sa.String(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('product_nutrition_facts',
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('protein_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fat_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('fiber_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('moisture_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('ash_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('kcal_per_100g', sa.Integer(), nullable=True),
    sa.Column('calcium_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('phosphorus_pct', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('aafco_statement', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.String(), server_default='now()', nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('product_id')
    )
    op.create_table('pet_food_allergies',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('allergen_code', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['allergen_code'], ['allergen_codes.code'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id', 'allergen_code')
    )
    op.create_table('pet_health_concerns',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('concern_code', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['concern_code'], ['health_concern_codes.code'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id', 'concern_code')
    )
    op.create_table('pet_other_allergies',
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('other_text', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('pet_id')
    )
    op.create_table('recommendation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('strategy', postgresql.ENUM('RULE_V1', 'RULE_V2', 'ML_V1', name='recstrategy', create_type=False), server_default='RULE_V1', nullable=False),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_rec_runs_pet_time', 'recommendation_runs', ['pet_id', 'created_at'], unique=False, postgresql_ops={'created_at': 'DESC'})
    op.create_table('recommendation_items',
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('score', sa.Numeric(precision=8, scale=4), nullable=False),
    sa.Column('reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['run_id'], ['recommendation_runs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('run_id', 'product_id')
    )
    op.create_index('idx_rec_items_run_rank', 'recommendation_items', ['run_id', 'rank'], unique=False)
    op.alter_column('alert_events', 'delta_percent',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               type_=sa.Numeric(precision=6, scale=2),
               existing_nullable=True)
    op.drop_index('ix_alert_events_alert_sent', table_name='alert_events')
    op.create_index('idx_alert_events_alert_time', 'alert_events', ['alert_id', 'sent_at'], unique=False, postgresql_ops={'sent_at': 'DESC'})
    op.drop_constraint('alert_events_alert_id_fkey', 'alert_events', type_='foreignkey')
    op.create_foreign_key(None, 'alert_events', 'alerts', ['alert_id'], ['id'], ondelete='CASCADE')
    op.drop_column('alert_events', 'updated_at')
    op.drop_index('ix_alerts_tracking_enabled', table_name='alerts')
    op.create_index('idx_alerts_tracking_enabled', 'alerts', ['tracking_id', 'is_enabled'], unique=False)
    op.drop_constraint('alerts_tracking_id_fkey', 'alerts', type_='foreignkey')
    op.create_foreign_key(None, 'alerts', 'trackings', ['tracking_id'], ['id'], ondelete='CASCADE')
    op.alter_column('outbound_clicks', 'offer_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.alter_column('outbound_clicks', 'source',
               existing_type=postgresql.ENUM('HOME', 'DETAIL', 'ALERT', name='clicksource'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.drop_index('ix_outbound_clicks_product_clicked', table_name='outbound_clicks')
    op.drop_index('ix_outbound_clicks_user_clicked', table_name='outbound_clicks')
    op.create_index('idx_clicks_product_time', 'outbound_clicks', ['product_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('idx_clicks_user_time', 'outbound_clicks', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.drop_constraint('outbound_clicks_pet_id_fkey', 'outbound_clicks', type_='foreignkey')
    op.drop_constraint('outbound_clicks_offer_id_fkey', 'outbound_clicks', type_='foreignkey')
    op.drop_constraint('outbound_clicks_product_id_fkey', 'outbound_clicks', type_='foreignkey')
    op.drop_constraint('outbound_clicks_user_id_fkey', 'outbound_clicks', type_='foreignkey')
    op.create_foreign_key(None, 'outbound_clicks', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'outbound_clicks', 'product_offers', ['offer_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'outbound_clicks', 'pets', ['pet_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'outbound_clicks', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.drop_column('outbound_clicks', 'updated_at')
    # 기존 데이터 처리를 위해 nullable=True로 먼저 추가
    op.add_column('pets', sa.Column('species', postgresql.ENUM('DOG', 'CAT', name='petspecies', create_type=False), nullable=True))
    op.add_column('pets', sa.Column('age_mode', postgresql.ENUM('BIRTHDATE', 'APPROX', name='ageinputmode', create_type=False), nullable=True))
    op.add_column('pets', sa.Column('birthdate', sa.Date(), nullable=True))
    op.add_column('pets', sa.Column('approx_age_months', sa.Integer(), nullable=True))
    op.add_column('pets', sa.Column('sex', postgresql.ENUM('MALE', 'FEMALE', 'UNKNOWN', name='petsex', create_type=False), server_default='UNKNOWN', nullable=True))
    op.add_column('pets', sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True))
    op.add_column('pets', sa.Column('body_condition_score', sa.Integer(), nullable=True))
    # 기존 데이터에 기본값 설정
    op.execute("UPDATE pets SET species = 'DOG' WHERE species IS NULL")
    op.execute("UPDATE pets SET age_mode = 'APPROX' WHERE age_mode IS NULL")
    op.execute("UPDATE pets SET sex = 'UNKNOWN' WHERE sex IS NULL")
    op.execute("UPDATE pets SET weight_kg = 10.0 WHERE weight_kg IS NULL")
    op.execute("UPDATE pets SET body_condition_score = 5 WHERE body_condition_score IS NULL")
    # 이제 NOT NULL 제약 추가
    op.alter_column('pets', 'species', nullable=False)
    op.alter_column('pets', 'age_mode', nullable=False)
    op.alter_column('pets', 'sex', nullable=False)
    op.alter_column('pets', 'weight_kg', nullable=False)
    op.alter_column('pets', 'body_condition_score', nullable=False)
    op.add_column('pets', sa.Column('photo_url', sa.String(length=500), nullable=True))
    # 기존 데이터에 name 기본값 설정
    op.execute("UPDATE pets SET name = '펫' WHERE name IS NULL")
    op.alter_column('pets', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=False)
    op.alter_column('pets', 'breed_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=True)
    op.drop_index('ix_pets_breed_weight_age', table_name='pets')
    op.create_index('idx_pets_age_stage', 'pets', ['age_stage'], unique=False)
    op.create_index('idx_pets_species_breed', 'pets', ['species', 'breed_code'], unique=False)
    op.drop_constraint('pets_user_id_fkey', 'pets', type_='foreignkey')
    op.create_foreign_key(None, 'pets', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('pets', 'weight_bucket_code')
    op.add_column('price_snapshots', sa.Column('listed_price', sa.Integer(), nullable=False))
    op.add_column('price_snapshots', sa.Column('shipping_fee', sa.Integer(), server_default='0', nullable=False))
    op.add_column('price_snapshots', sa.Column('coupon_discount', sa.Integer(), server_default='0', nullable=False))
    op.add_column('price_snapshots', sa.Column('card_discount', sa.Integer(), server_default='0', nullable=False))
    op.add_column('price_snapshots', sa.Column('final_price', sa.Integer(), nullable=False))
    op.add_column('price_snapshots', sa.Column('is_sold_out', sa.Boolean(), server_default='false', nullable=False))
    op.drop_index('ix_price_snapshots_offer_captured', table_name='price_snapshots')
    op.create_index('idx_price_snapshots_offer_final', 'price_snapshots', ['offer_id', 'final_price'], unique=False)
    op.create_index('idx_price_snapshots_offer_time', 'price_snapshots', ['offer_id', 'captured_at'], unique=False, postgresql_ops={'captured_at': 'DESC'})
    op.drop_constraint('price_snapshots_offer_id_fkey', 'price_snapshots', type_='foreignkey')
    op.create_foreign_key(None, 'price_snapshots', 'product_offers', ['offer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('price_snapshots', 'price')
    op.drop_column('price_snapshots', 'updated_at')
    op.add_column('price_summaries', sa.Column('avg_final_price', sa.Integer(), nullable=False))
    op.add_column('price_summaries', sa.Column('min_final_price', sa.Integer(), nullable=False))
    op.add_column('price_summaries', sa.Column('max_final_price', sa.Integer(), nullable=False))
    op.add_column('price_summaries', sa.Column('last_final_price', sa.Integer(), nullable=False))
    op.drop_constraint('price_summaries_offer_id_key', 'price_summaries', type_='unique')
    op.drop_constraint('price_summaries_offer_id_fkey', 'price_summaries', type_='foreignkey')
    op.create_foreign_key(None, 'price_summaries', 'product_offers', ['offer_id'], ['id'], ondelete='CASCADE')
    op.drop_column('price_summaries', 'last_price')
    op.drop_column('price_summaries', 'min_price')
    op.drop_column('price_summaries', 'avg_price')
    op.drop_column('price_summaries', 'max_price')
    op.drop_column('price_summaries', 'id')
    op.drop_column('price_summaries', 'created_at')
    op.add_column('product_offers', sa.Column('seller_name', sa.String(length=120), nullable=True))
    op.add_column('product_offers', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.create_index('idx_offers_active', 'product_offers', ['is_active'], unique=False)
    op.drop_constraint('product_offers_product_id_fkey', 'product_offers', type_='foreignkey')
    op.create_foreign_key(None, 'product_offers', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.add_column('products', sa.Column('species', postgresql.ENUM('DOG', 'CAT', name='petspecies', create_type=False), nullable=True))
    op.alter_column('products', 'category',
               existing_type=postgresql.ENUM('FOOD', name='productcategory'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.create_index('idx_products_active', 'products', ['is_active'], unique=False)
    op.create_index('idx_products_brand', 'products', ['brand_name'], unique=False)
    op.drop_column('products', 'internal_tags')
    op.create_index('idx_trackings_pet', 'trackings', ['pet_id'], unique=False)
    op.create_index('idx_trackings_product', 'trackings', ['product_id'], unique=False)
    op.create_index('idx_trackings_user', 'trackings', ['user_id'], unique=False)
    op.drop_constraint('trackings_user_id_fkey', 'trackings', type_='foreignkey')
    op.drop_constraint('trackings_pet_id_fkey', 'trackings', type_='foreignkey')
    op.drop_constraint('trackings_product_id_fkey', 'trackings', type_='foreignkey')
    op.create_foreign_key(None, 'trackings', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'trackings', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'trackings', 'pets', ['pet_id'], ['id'], ondelete='CASCADE')
    # 기존 데이터 처리를 위해 nullable=True로 먼저 추가
    op.add_column('users', sa.Column('nickname', sa.String(length=50), nullable=True))
    # 기존 데이터에 기본값 설정 (provider_user_id를 사용하거나 기본값 사용)
    op.execute("UPDATE users SET nickname = COALESCE(email, 'user_' || SUBSTRING(provider_user_id::text, 1, 8)) WHERE nickname IS NULL")
    # 이제 NOT NULL 제약 추가
    op.alter_column('users', 'nickname', nullable=False)
    op.drop_index('ix_users_email', table_name='users')
    op.create_index('idx_users_nickname', 'users', ['nickname'], unique=False)
    op.create_index('idx_users_provider_user_id', 'users', ['provider', 'provider_user_id'], unique=False)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    op.drop_index('idx_users_provider_user_id', table_name='users')
    op.drop_index('idx_users_nickname', table_name='users')
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.drop_column('users', 'nickname')
    op.drop_constraint(None, 'trackings', type_='foreignkey')
    op.drop_constraint(None, 'trackings', type_='foreignkey')
    op.drop_constraint(None, 'trackings', type_='foreignkey')
    op.create_foreign_key('trackings_product_id_fkey', 'trackings', 'products', ['product_id'], ['id'])
    op.create_foreign_key('trackings_pet_id_fkey', 'trackings', 'pets', ['pet_id'], ['id'])
    op.create_foreign_key('trackings_user_id_fkey', 'trackings', 'users', ['user_id'], ['id'])
    op.drop_index('idx_trackings_user', table_name='trackings')
    op.drop_index('idx_trackings_product', table_name='trackings')
    op.drop_index('idx_trackings_pet', table_name='trackings')
    op.add_column('products', sa.Column('internal_tags', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_index('idx_products_brand', table_name='products')
    op.drop_index('idx_products_active', table_name='products')
    op.alter_column('products', 'category',
               existing_type=sa.String(length=30),
               type_=postgresql.ENUM('FOOD', name='productcategory'),
               existing_nullable=False)
    op.drop_column('products', 'species')
    op.drop_constraint(None, 'product_offers', type_='foreignkey')
    op.create_foreign_key('product_offers_product_id_fkey', 'product_offers', 'products', ['product_id'], ['id'])
    op.drop_index('idx_offers_active', table_name='product_offers')
    op.drop_column('product_offers', 'is_active')
    op.drop_column('product_offers', 'seller_name')
    op.add_column('price_summaries', sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('price_summaries', sa.Column('id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('price_summaries', sa.Column('max_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('price_summaries', sa.Column('avg_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('price_summaries', sa.Column('min_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('price_summaries', sa.Column('last_price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_summaries', type_='foreignkey')
    op.create_foreign_key('price_summaries_offer_id_fkey', 'price_summaries', 'product_offers', ['offer_id'], ['id'])
    op.create_unique_constraint('price_summaries_offer_id_key', 'price_summaries', ['offer_id'])
    op.drop_column('price_summaries', 'last_final_price')
    op.drop_column('price_summaries', 'max_final_price')
    op.drop_column('price_summaries', 'min_final_price')
    op.drop_column('price_summaries', 'avg_final_price')
    op.add_column('price_snapshots', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('price_snapshots', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'price_snapshots', type_='foreignkey')
    op.create_foreign_key('price_snapshots_offer_id_fkey', 'price_snapshots', 'product_offers', ['offer_id'], ['id'])
    op.drop_index('idx_price_snapshots_offer_time', table_name='price_snapshots', postgresql_ops={'captured_at': 'DESC'})
    op.drop_index('idx_price_snapshots_offer_final', table_name='price_snapshots')
    op.create_index('ix_price_snapshots_offer_captured', 'price_snapshots', ['offer_id', sa.text('captured_at DESC')], unique=False)
    op.drop_column('price_snapshots', 'is_sold_out')
    op.drop_column('price_snapshots', 'final_price')
    op.drop_column('price_snapshots', 'card_discount')
    op.drop_column('price_snapshots', 'coupon_discount')
    op.drop_column('price_snapshots', 'shipping_fee')
    op.drop_column('price_snapshots', 'listed_price')
    op.add_column('pets', sa.Column('weight_bucket_code', sa.VARCHAR(length=20), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'pets', type_='foreignkey')
    op.create_foreign_key('pets_user_id_fkey', 'pets', 'users', ['user_id'], ['id'])
    op.drop_index('idx_pets_species_breed', table_name='pets')
    op.drop_index('idx_pets_age_stage', table_name='pets')
    op.create_index('ix_pets_breed_weight_age', 'pets', ['breed_code', 'weight_bucket_code', 'age_stage'], unique=False)
    op.alter_column('pets', 'breed_code',
               existing_type=sa.VARCHAR(length=50),
               nullable=False)
    op.alter_column('pets', 'name',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_column('pets', 'photo_url')
    op.drop_column('pets', 'body_condition_score')
    op.drop_column('pets', 'weight_kg')
    op.drop_column('pets', 'sex')
    op.drop_column('pets', 'approx_age_months')
    op.drop_column('pets', 'birthdate')
    op.drop_column('pets', 'age_mode')
    op.drop_column('pets', 'species')
    op.add_column('outbound_clicks', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'outbound_clicks', type_='foreignkey')
    op.drop_constraint(None, 'outbound_clicks', type_='foreignkey')
    op.drop_constraint(None, 'outbound_clicks', type_='foreignkey')
    op.drop_constraint(None, 'outbound_clicks', type_='foreignkey')
    op.create_foreign_key('outbound_clicks_user_id_fkey', 'outbound_clicks', 'users', ['user_id'], ['id'])
    op.create_foreign_key('outbound_clicks_product_id_fkey', 'outbound_clicks', 'products', ['product_id'], ['id'])
    op.create_foreign_key('outbound_clicks_offer_id_fkey', 'outbound_clicks', 'product_offers', ['offer_id'], ['id'])
    op.create_foreign_key('outbound_clicks_pet_id_fkey', 'outbound_clicks', 'pets', ['pet_id'], ['id'])
    op.drop_index('idx_clicks_user_time', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.drop_index('idx_clicks_product_time', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.create_index('ix_outbound_clicks_user_clicked', 'outbound_clicks', ['user_id', sa.text('clicked_at DESC')], unique=False)
    op.create_index('ix_outbound_clicks_product_clicked', 'outbound_clicks', ['product_id', sa.text('clicked_at DESC')], unique=False)
    op.alter_column('outbound_clicks', 'source',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('HOME', 'DETAIL', 'ALERT', name='clicksource'),
               existing_nullable=False)
    op.alter_column('outbound_clicks', 'offer_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'alerts', type_='foreignkey')
    op.create_foreign_key('alerts_tracking_id_fkey', 'alerts', 'trackings', ['tracking_id'], ['id'])
    op.drop_index('idx_alerts_tracking_enabled', table_name='alerts')
    op.create_index('ix_alerts_tracking_enabled', 'alerts', ['tracking_id', 'is_enabled'], unique=False)
    op.add_column('alert_events', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'alert_events', type_='foreignkey')
    op.create_foreign_key('alert_events_alert_id_fkey', 'alert_events', 'alerts', ['alert_id'], ['id'])
    op.drop_index('idx_alert_events_alert_time', table_name='alert_events', postgresql_ops={'sent_at': 'DESC'})
    op.create_index('ix_alert_events_alert_sent', 'alert_events', ['alert_id', sa.text('sent_at DESC')], unique=False)
    op.alter_column('alert_events', 'delta_percent',
               existing_type=sa.Numeric(precision=6, scale=2),
               type_=sa.NUMERIC(precision=5, scale=2),
               existing_nullable=True)
    op.drop_index('idx_rec_items_run_rank', table_name='recommendation_items')
    op.drop_table('recommendation_items')
    op.drop_index('idx_rec_runs_pet_time', table_name='recommendation_runs', postgresql_ops={'created_at': 'DESC'})
    op.drop_table('recommendation_runs')
    op.drop_table('pet_other_allergies')
    op.drop_table('pet_health_concerns')
    op.drop_table('pet_food_allergies')
    op.drop_table('product_nutrition_facts')
    op.drop_table('product_ingredient_profiles')
    op.drop_index('idx_product_claims_claim', table_name='product_claims')
    op.drop_table('product_claims')
    op.drop_index('idx_product_allergens_allergen', table_name='product_allergens')
    op.drop_table('product_allergens')
    op.drop_table('health_concern_codes')
    op.drop_table('claim_codes')
    op.drop_table('allergen_codes')
    # ### end Alembic commands ###

