"""init

Revision ID: ec9dc2d37528
Revises: 
Create Date: 2026-01-26 00:13:25.726826

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ec9dc2d37528'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('products',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.Enum('FOOD', name='productcategory'), nullable=False),
    sa.Column('brand_name', sa.String(length=100), nullable=False),
    sa.Column('product_name', sa.String(length=255), nullable=False),
    sa.Column('size_label', sa.String(length=50), nullable=True),
    sa.Column('internal_tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_user_id', sa.String(length=255), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', 'provider_user_id', name='uq_user_provider')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=False)
    op.create_table('pets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('breed_code', sa.String(length=50), nullable=False),
    sa.Column('weight_bucket_code', sa.String(length=20), nullable=False),
    sa.Column('age_stage', sa.Enum('PUPPY', 'ADULT', 'SENIOR', name='agestage'), nullable=False),
    sa.Column('is_neutered', sa.Boolean(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_pets_breed_weight_age', 'pets', ['breed_code', 'weight_bucket_code', 'age_stage'], unique=False)
    op.create_index(op.f('ix_pets_user_id'), 'pets', ['user_id'], unique=False)
    op.create_table('product_offers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('merchant', sa.Enum('COUPANG', 'NAVER', 'BRAND', name='merchant'), nullable=False),
    sa.Column('merchant_product_id', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('affiliate_url', sa.String(length=500), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('merchant', 'merchant_product_id', name='uq_offer_merchant_product')
    )
    op.create_index('ix_offers_product_merchant', 'product_offers', ['product_id', 'merchant'], unique=False)
    op.create_index(op.f('ix_product_offers_product_id'), 'product_offers', ['product_id'], unique=False)
    op.create_table('outbound_clicks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=True),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('source', sa.Enum('HOME', 'DETAIL', 'ALERT', name='clicksource'), nullable=False),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('session_id', sa.String(length=255), nullable=True),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['product_offers.id'], ),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_outbound_clicks_product_clicked', 'outbound_clicks', ['product_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.create_index(op.f('ix_outbound_clicks_product_id'), 'outbound_clicks', ['product_id'], unique=False)
    op.create_index('ix_outbound_clicks_user_clicked', 'outbound_clicks', ['user_id', 'clicked_at'], unique=False, postgresql_ops={'clicked_at': 'DESC'})
    op.create_index(op.f('ix_outbound_clicks_user_id'), 'outbound_clicks', ['user_id'], unique=False)
    op.create_table('price_snapshots',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('price', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('meta', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['product_offers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_price_snapshots_offer_captured', 'price_snapshots', ['offer_id', 'captured_at'], unique=False, postgresql_ops={'captured_at': 'DESC'})
    op.create_index(op.f('ix_price_snapshots_offer_id'), 'price_snapshots', ['offer_id'], unique=False)
    op.create_table('price_summaries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('offer_id', sa.UUID(), nullable=False),
    sa.Column('window_days', sa.Integer(), nullable=False),
    sa.Column('avg_price', sa.Integer(), nullable=False),
    sa.Column('min_price', sa.Integer(), nullable=False),
    sa.Column('max_price', sa.Integer(), nullable=False),
    sa.Column('last_price', sa.Integer(), nullable=False),
    sa.Column('last_captured_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['offer_id'], ['product_offers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('offer_id')
    )
    op.create_table('trackings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('pet_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'DELETED', name='trackingstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['pet_id'], ['pets.id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'pet_id', 'product_id', name='uq_tracking_user_pet_product')
    )
    op.create_index(op.f('ix_trackings_pet_id'), 'trackings', ['pet_id'], unique=False)
    op.create_index(op.f('ix_trackings_product_id'), 'trackings', ['product_id'], unique=False)
    op.create_index(op.f('ix_trackings_user_id'), 'trackings', ['user_id'], unique=False)
    op.create_table('alerts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tracking_id', sa.UUID(), nullable=False),
    sa.Column('rule_type', sa.Enum('BELOW_AVG', 'NEW_LOW', 'TARGET_PRICE', name='alertruletype'), nullable=False),
    sa.Column('target_price', sa.Integer(), nullable=True),
    sa.Column('cooldown_hours', sa.Integer(), nullable=False),
    sa.Column('is_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_triggered_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['tracking_id'], ['trackings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_alerts_tracking_enabled', 'alerts', ['tracking_id', 'is_enabled'], unique=False)
    op.create_index(op.f('ix_alerts_tracking_id'), 'alerts', ['tracking_id'], unique=False)
    op.create_table('alert_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('alert_id', sa.UUID(), nullable=False),
    sa.Column('trigger_reason', sa.Enum('BELOW_AVG', 'NEW_LOW', 'TARGET_PRICE', name='alertruletype'), nullable=False),
    sa.Column('price_at_trigger', sa.Integer(), nullable=False),
    sa.Column('avg_price_at_trigger', sa.Integer(), nullable=True),
    sa.Column('delta_percent', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('opened_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('clicked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SENT', 'FAILED', name='alerteventstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alert_events_alert_id'), 'alert_events', ['alert_id'], unique=False)
    op.create_index('ix_alert_events_alert_sent', 'alert_events', ['alert_id', 'sent_at'], unique=False, postgresql_ops={'sent_at': 'DESC'})
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_alert_events_alert_sent', table_name='alert_events', postgresql_ops={'sent_at': 'DESC'})
    op.drop_index(op.f('ix_alert_events_alert_id'), table_name='alert_events')
    op.drop_table('alert_events')
    op.drop_index(op.f('ix_alerts_tracking_id'), table_name='alerts')
    op.drop_index('ix_alerts_tracking_enabled', table_name='alerts')
    op.drop_table('alerts')
    op.drop_index(op.f('ix_trackings_user_id'), table_name='trackings')
    op.drop_index(op.f('ix_trackings_product_id'), table_name='trackings')
    op.drop_index(op.f('ix_trackings_pet_id'), table_name='trackings')
    op.drop_table('trackings')
    op.drop_table('price_summaries')
    op.drop_index(op.f('ix_price_snapshots_offer_id'), table_name='price_snapshots')
    op.drop_index('ix_price_snapshots_offer_captured', table_name='price_snapshots', postgresql_ops={'captured_at': 'DESC'})
    op.drop_table('price_snapshots')
    op.drop_index(op.f('ix_outbound_clicks_user_id'), table_name='outbound_clicks')
    op.drop_index('ix_outbound_clicks_user_clicked', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.drop_index(op.f('ix_outbound_clicks_product_id'), table_name='outbound_clicks')
    op.drop_index('ix_outbound_clicks_product_clicked', table_name='outbound_clicks', postgresql_ops={'clicked_at': 'DESC'})
    op.drop_table('outbound_clicks')
    op.drop_index(op.f('ix_product_offers_product_id'), table_name='product_offers')
    op.drop_index('ix_offers_product_merchant', table_name='product_offers')
    op.drop_table('product_offers')
    op.drop_index(op.f('ix_pets_user_id'), table_name='pets')
    op.drop_index('ix_pets_breed_weight_age', table_name='pets')
    op.drop_table('pets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('products')
    # ### end Alembic commands ###

